name: med_voy
description: "A Medical Application"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
#  state Management
  flutter_bloc: ^8.1.3
#  Code Generator and Annotation For Freezed-code Generation
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1

#  for Dependency injection
  get_it: ^7.6.7
#  Annotation for json_serializable code-generator
  json_annotation: ^4.8.1
#  HTTP networking package, supports Interceptors, Aborting and canceling a request, Custom adapters, Transformers, etc.
  dio: ^5.4.0
  retrofit: ^4.1.0
#  deal with internationalized/localized messages, date and number formatting and parsing, bi-directional text, and other internationalization issues.
  intl: ^0.18.0
#  Easy and Fast internationalizing and localization your Flutter Apps
  easy_localization: ^3.0.3
#  Customize Flutter's default white native splash screen with background color and splash image.
  flutter_native_splash: ^2.3.10
#  An SVG rendering, which allows painting and displaying Scalable Vector Graphics 1.1 files.
  flutter_svg: ^2.0.9
#  A flutter plugin for adapting screen and font size.Guaranteed to look good on different models
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
#  Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.7.1
#  A dio client generator using source_gen to help retrofit package
  retrofit_generator: ^8.1.0
#  A Dio interceptor that logs network calls in a pretty, easy to read format.
  pretty_dio_logger: ^1.3.1
flutter:

  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
